from distutils.core import setup

setup(
    name='pyGeoNet 1.0',
    version='1.0.0',
    author='Harish Sangireddy',
    author_email='hsangireddy@utexas.edu,harish2rb@gmail.com',
    packages=['pygeonet', 'pygeonet.test'],
    license='LICENSE.txt',
    description='Geomorphic feature extraction toolbox',
    long_description=open('C:\\Users\\Harish\\Documents\\GitHub\\pyGeoNet\\README.txt').read(),
    install_requires=[
        'argparse==1.2.1',
        'backports.ssl-match-hostname==3.4.0.2',
        'bottleneck==0.8.0',
        'certifi==14.05.14',
        'cython==0.20.2',
        'gdal==1.11.0',
        'jinja2==2.7.3',
        'markupsafe==0.23',
        'matplotlib==1.3.1',
        'numpy==1.8.2',
        'pandas==0.14.1',
        'patsy==0.3.0',
        'pyparsing==2.0.2',
        'pyreadline==2.0',
        'python-dateutil==2.2',
        'pytz==2014.4',
        'pyzmq==14.3.1',
        'scikit-fmm==0.0.5',
        'scipy==0.14.0',
        'six==1.7.3',
        'statsmodels==0.5.0',
        'stevedore==0.15',
        'tornado==4.0.2',
        'virtualenv-clone==0.2.5',
        'virtualenvwrapper==4.3.1'
    ],
)
